version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cmce_db
      POSTGRES_USER: cmce_user
      POSTGRES_PASSWORD: cmce_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: