# Generated by Django 5.2.1 on 2025-05-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_recipe_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
